version: '3.8'

services:
  appbookinghall:
    build: .
    container_name: appbookinghall
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./server.js:/usr/src/app/server.js
      - ./.env:/usr/src/app/.env
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      dbbookinghall:
        condition: service_healthy
    networks:
      - bookinghallnetwork

  dbbookinghall:
    image: mysql:8.0
    container_name: dbbookinghall
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookinghalldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123ABc;#789
    volumes:
      - bookinghall-data:/var/lib/mysql
    ports:
      - "3307:3306"  # Changé de 3306:3306 à 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - bookinghallnetwork

volumes:
  bookinghall-data:

networks:
  bookinghallnetwork:
    driver: bridge